language: java
jdk:
  - openjdk8
  - openjdk12

services:
  - docker


jobs:
  include:
    - stage: test
      script: "gradle clean test"
    - stage: check
      script: "./gradlew check --info --stacktrace"