version: '3'
services:
  web:
    container_name: sporttoolbox
    build: .
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dockercompose"
    networks:
      network:
        ipv4_address: 172.28.1.1
    depends_on:
      - heatmap-provider
  heatmap-provider:
    container_name: heatmap-provider
    image: segelzwerg/heatmap-provider:stable
    # build:
    #  ./Heatmap-Provider
    ports:
      - "5000:5000"
    networks:
      network:
        ipv4_address: 172.28.1.2

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16